---
title: "Example-analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example-analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(devtools)
library(ggplot2)
library(doParallel)
library(lme4)
library(psych)

document()
library(QualityMeasure)
```


# Introduction
This vignette shows how to use the functions in qmrel to analzye quality measure performance.

First we'll simulate some data.

```{r}
n.entity = 100
n = rpois(n.entity, 200)
p = rbeta(n.entity, 1, 50) 
df <- simulateData(n = n, p = p)
```


# Calculate reliability

```{r}
rel.results <- calcReliability(df = df)
```


# Plot number of observations per provider

```{r}
plotN(rel.results$perf.res$perf.results$n)
```

# Plot measure performance

```{r}
plotPerformance(rel.results$perf.res$perf.results)
plotPerformance(rel.results$perf.res$perf.results, 'rs')

```

# Reliability estimates

```{r}
rel.results$rel.results
```
